# Generated by Django 3.1 on 2020-11-12 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'beverage',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date', models.DateField()),
                ('open', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sandwich',
            },
        ),
        migrations.CreateModel(
            name='SandwichOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.purchase')),
                ('sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sandwich')),
            ],
            options={
                'db_table': 'sandwich_order',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='SandwichValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sandwich')),
            ],
            options={
                'db_table': 'sandwich_value',
            },
        ),
        migrations.CreateModel(
            name='SandwichStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('sandwich_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sandwichorder')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
            options={
                'db_table': 'sandwich_status',
            },
        ),
        migrations.CreateModel(
            name='SandwichIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
                ('sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sandwich')),
            ],
            options={
                'db_table': 'sandwich_ingredient',
            },
        ),
        migrations.CreateModel(
            name='OrderedIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
                ('sandwich_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sandwichorder')),
            ],
            options={
                'db_table': 'ordered_ingredients',
            },
        ),
        migrations.CreateModel(
            name='IngredientValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
            options={
                'db_table': 'ingredient_value',
            },
        ),
        migrations.CreateModel(
            name='BeverageValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beverage')),
            ],
            options={
                'db_table': 'beverage_value',
            },
        ),
        migrations.CreateModel(
            name='BeverageOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beverage')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.purchase')),
            ],
            options={
                'db_table': 'beverage_order',
            },
        ),
    ]
