# Generated by Django 3.1 on 2020-11-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandwichvalue',
            name='value',
        ),
        migrations.AddField(
            model_name='sandwichvalue',
            name='percent',
            field=models.FloatField(default=5),
        ),
    ]
